name: PR Commit CI
on:
  push:
    branches:
      - "**"

jobs:
  ci:
    name: Commit verification
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install packages
        run: npm install --frozen-lockfile

      - name: Analyze
        run: npm run analyze
